language: bash

services:
  - docker

before_install:
  - docker build -t my-web-app .

script:
  - docker run -d -p 6756:80 my-web-app
  - sleep 3 # wait for nginx to start
  - response=$(curl --write-out %{http_code} --silent --output /dev/null localhost:6756)
  - if [ $response != "200" ]; then exit 1; fi

deploy:
  - provider: elasticbeanstalk
    region: ap-south-1
    app: "devops-mini-project"
    env: "Devopsminiproject-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SERECT_KEY

    bucket_name: "devops-mini-project"

    bucket_path: "docker"

    on:
      branch: main