language: bash

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t my-web-app .
  
script:
  - docker run -d -p 6756:80 my-web-app
  - sleep 3 # wait for nginx to start
  - response=$(curl --write-out %{http_code} --silent --output /dev/null localhost:6756)
  - if [ $response != "200" ]; then exit 1; fi
  
deploy:
  provider: heroku
  api_key: "$HEROKU_KEY"  
  app: devops-pro
  on:
    branch: deploy-test
