language: bash
sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t my-web-app .
  
script:
  - docker build -t my-web-app .
#  - docker tag my-web-app registry.heroku.com/$HEROKU_APP/web 
  - sleep 4 # wait for nginx to start
  - response=$(curl --write-out %{http_code} --silent --output /dev/null localhost:6756)
  - if [ $response != "200" ]; then exit 1; fi
  
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: devops-mini-project
  env: Devopsminiproject-env

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SERECT_KEY

  bucket_name: "devops-mini-project"

  bucket_path: "docker"

  on:
    branch: test01

 
