language: shell

services:
  - docker


before_script:
  - docker build -t  .

script:
  - docker run 

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: your-heroku-app-name
  on:
    branch: main
