language: bash

services:
  - docker

before_install:
  - sudo apt-get install sshpass
  - docker build -t my-web-app .

script:
  - docker run -d -p 6756:80 my-web-app
  - sleep 5 # wait for nginx to start
  - response=$(curl --write-out %{http_code} --silent --output /dev/null localhost:6756)
  - if [ $response != "200" ]; then exit 1; fi

after_success:
  - echo "Deployment started"
  - sshpass -p '$vm_pass' scp -o StrictHostKeyChecking=no my-web-app root@142.93.217.53:/tmp/my-web-app
  - sshpass -p '$vm_pass' ssh root@142.93.217.53 "docker stop my-web-app && docker rm my-web-app && docker load < /tmp/my-web-app && docker run -d -p 80:80 --name my-web-app my-web-app"
  - echo "Deployment finished successfully"
