language: shell

services:
  - docker


before_script:
  - docker build -t your-docker-image-name .

script:
  - docker run your-docker-image-name python test.py

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: your-heroku-app-name
  on:
    branch: main
