language: bash

services:
  - docker

before_install:
  - sudo apt-get install sshpass

script:
  # Build and tag the Docker image
  - docker build -t reddy0718/devops-project:v1 .

  # Test the Docker image
  - docker run -d -p 8080:80 reddy0718/devops-project:v1
  - sleep 5 # wait for nginx to start
  - response=$(curl --write-out %{http_code} --silent --output /dev/null localhost:8080)
  - if [ $response != "200" ]; then exit 1; fi
  - echo  "test passed" 

after_success:
  # Log in to Docker Hub using access token
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push the Docker image to Docker Hub
  - docker push reddy0718/devops-project:v1

  - echo "$ssh_key" > ssh_key.key
  - cat ssh_key.key
  - echo $vm_ip
  - chmod 400 ssh_key.key
  - ssh -i ssh_key.key -o StrictHostKeyChecking=no root@$vm_ip "docker login && docker pull reddy0718/devops-project:v1" 
  # SSH into the VM and pull the Docker image
  # - sshpass -p "$vm_pass" ssh "root@$vm_ip" "docker login && docker pull reddy0718/devops-project:v1"

  # Spin up the Docker container
  - ssh -i ssh_key.key root@$vm_ip "docker stop my-web-app && docker rm my-web-app && docker run -d -p 6060:6060 --name my-web-app reddy0718/devops-project:v1 && docker rmi $(docker images -qf dangling=true) || true"
  # - sshpass -p "$vm_pass" ssh "root@$vm_ip" "docker stop my-web-app && docker rm my-web-app && docker run -d -p 6060:6060 --name my-web-app reddy0718/devops-project:v1 && docker rmi $(docker images -qf dangling=true) || true"
