name: Deploy to Server

on:
    push:
        branches:
            - main

env:
    PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    HOSTNAME: ${{ secrets.SERVER_IP }}
    USERNAME: ${{ secrets.SERVER_USERNAME }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                port: "22"
                script: |
                  echo "Hello, world!"