name: Deploy to Server

on:
    push:
        branches:
            - main

env:
    PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    HOSTNAME: ${{ secrets.SERVER_IP }}
    USERNAME: ${{ secrets.SERVER_USERNAME }}

jobs:
    continuous-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: reddy0718/devops-project
                
            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: .
                push: true
                tags: reddy0718/devops-project:v1

            - uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                port: "22"
                script: |
                  echo "Hello, world!"
                  docker login && docker pull reddy0718/devops-project:v1
                  docker stop my-web-app && docker rm my-web-app && docker run -d -p 6060:6060 --name my-web-app reddy0718/devops-project:v1 && docker rmi $(docker images -qf dangling=true) || true