name: Deploy to Server

on:
    push:
        branches:
            - main

env:
    PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    HOSTNAME: ${{ secrets.SERVER_IP }}
    USERNAME: ${{ secrets.SERVER_USERNAME }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Adding Known Hosts
              run: |
                echo "$PRIVATE_KEY" > ssh_key
                chmod 600 ssh_key

            - name: Copy code to server
              run: ssh -o StrictHostKeyChecking=no -i ssh_key $USERNAME@$HOSTNAME "docker -v"